import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import styles from "../css/Navbar.module.css";
import tele from "../img/telephone.png";
import cart from "../img/cart.png";
import logo from "../img/logo.png";
import { Link } from "react-router-dom";
const Navbar = () => {
    return (_jsxs("div", Object.assign({ className: styles.container }, { children: [_jsxs("div", Object.assign({ className: styles.item }, { children: [_jsx("div", Object.assign({ className: styles.callButton }, { children: _jsx("img", { src: tele, alt: "", width: "32", height: "32" }) })), _jsxs("div", Object.assign({ className: styles.texts }, { children: [_jsx("div", Object.assign({ className: styles.text }, { children: "ORDER NOW!" })), _jsx("div", Object.assign({ className: styles.text }, { children: "012 345 678" }))] }))] })), _jsx("div", Object.assign({ className: styles.item }, { children: _jsxs("ul", Object.assign({ className: styles.list }, { children: [_jsx("li", Object.assign({ className: styles.listItem }, { children: _jsx(Link, Object.assign({ to: "/" }, { children: "Home" })) })), _jsx("li", Object.assign({ className: styles.listItem }, { children: _jsx(Link, Object.assign({ to: "/Products" }, { children: "Products" })) })), _jsx("li", Object.assign({ className: styles.listItem }, { children: _jsx(Link, Object.assign({ to: "/menu" }, { children: "Menu" })) })), _jsx("img", { src: logo, alt: "", width: "100px", height: "100px" }), _jsx("li", Object.assign({ className: styles.listItem }, { children: _jsx(Link, Object.assign({ to: "/events" }, { children: "Events" })) })), _jsxs("li", Object.assign({ className: styles.listItem }, { children: [" ", _jsx(Link, Object.assign({ to: "/blog" }, { children: "Blog" }))] })), _jsxs("li", Object.assign({ className: styles.listItem }, { children: [" ", _jsx(Link, Object.assign({ to: "/contact" }, { children: "Contact" }))] }))] })) })), _jsx("div", Object.assign({ className: styles.item }, { children: _jsxs("div", Object.assign({ className: styles.cart }, { children: [_jsx("img", { src: cart, alt: "", width: "30px", height: "30px" }), _jsx("div", Object.assign({ className: styles.counter }, { children: "2" }))] })) }))] })));
};
export default Navbar;
